import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

/**
 * LESC compiler.
 *
 * LESC is the scripting language for Joytopia 2. This first compiler targets
 * browser JavaScript so LESC scripts can control the Joytopia 2 web runtime.
 *
 * Usage:
 *   javac LESC.java
 *   java LESC main.lesc
 *   java LESC main.lesc game-script.js
 */
public class LESC {
    private static final String HEADER = "// Generated by LESC compiler for Joytopia 2\n" +
            "// Do not edit generated files directly.\n\n";

    public static void main(String[] args) {
        if (args.length < 1 || args.length > 2) {
            System.out.println("LESC Compiler - Joytopia 2");
            System.out.println("Usage: java LESC <input.lesc> [output.js]");
            System.exit(1);
        }

        Path input = Paths.get(args[0]);
        Path output = args.length == 2
                ? Paths.get(args[1])
                : defaultOutput(input);

        try {
            String source = Files.readString(input);
            String js = compile(source, input.toString());
            Files.writeString(output, js);
            System.out.println("LESC: compiled " + input + " -> " + output);
        } catch (IOException | LESCException e) {
            System.err.println("LESC ERROR: " + e.getMessage());
            System.exit(2);
        }
    }

    private static Path defaultOutput(Path input) {
        String name = input.getFileName().toString();
        if (name.toLowerCase().endsWith(".lesc")) {
            name = name.substring(0, name.length() - 5) + ".js";
        } else {
            name += ".js";
        }
        Path parent = input.getParent();
        return parent == null ? Paths.get(name) : parent.resolve(name);
    }

    public static String compile(String source, String filename) throws LESCException {
        List<String> lines = source.replace("\r\n", "\n").replace('\r', '\n').lines().toList();
        StringBuilder out = new StringBuilder(HEADER);
        int indent = 0;
        boolean inFunction = false;

        for (int i = 0; i < lines.size(); i++) {
            String raw = lines.get(i);
            String line = stripComment(raw).trim();
            if (line.isEmpty()) continue;

            int lineNumber = i + 1;

            if (line.equals("end")) {
                if (indent == 0) error(filename, lineNumber, "unexpected 'end'");
                indent--;
                if (inFunction && indent == 0) inFunction = false;
                emit(out, indent, "}");
                continue;
            }

            if (line.startsWith("function ")) {
                String declaration = line.substring(9).trim();
                int open = declaration.indexOf('(');
                int close = declaration.lastIndexOf(')');
                if (open <= 0 || close < open) {
                    error(filename, lineNumber, "invalid function declaration");
                }
                String name = declaration.substring(0, open).trim();
                String args = declaration.substring(open + 1, close).trim();
                validateIdentifier(name, filename, lineNumber);
                emit(out, indent, "function " + name + "(" + args + ") {");
                indent++;
                inFunction = true;
                continue;
            }

            if (line.startsWith("if ")) {
                String condition = line.substring(3).trim();
                if (condition.endsWith(" then")) condition = condition.substring(0, condition.length() - 5).trim();
                emit(out, indent, "if (" + expression(condition) + ") {");
                indent++;
                continue;
            }

            if (line.startsWith("while ")) {
                String condition = line.substring(6).trim();
                if (condition.endsWith(" do")) condition = condition.substring(0, condition.length() - 3).trim();
                emit(out, indent, "while (" + expression(condition) + ") {");
                indent++;
                continue;
            }

            if (line.startsWith("repeat ")) {
                String count = line.substring(7).trim();
                emit(out, indent, "for (let __i = 0; __i < " + expression(count) + "; __i++) {");
                indent++;
                continue;
            }

            if (line.equals("else")) {
                if (indent == 0) error(filename, lineNumber, "'else' without matching 'if'");
                indent--;
                emit(out, indent, "} else {");
                indent++;
                continue;
            }

            if (line.startsWith("print(") || line.startsWith("print (")) {
                emit(out, indent, "console.log" + line.substring(line.indexOf('(')) + ";");
                continue;
            }

            if (line.startsWith("alert(") || line.startsWith("alert (")) {
                emit(out, indent, "window.alert" + line.substring(line.indexOf('(')) + ";");
                continue;
            }

            if (line.startsWith("wait(") || line.startsWith("wait (")) {
                String arg = insideCall(line, "wait", filename, lineNumber);
                emit(out, indent, "await new Promise(__resolve => setTimeout(__resolve, " + expression(arg) + " * 1000));");
                continue;
            }

            if (line.equals("spawn()") || line.equals("spawn ()")) {
                emit(out, indent, "Joytopia.spawn();");
                continue;
            }

            if (line.startsWith("broadcast ")) {
                String value = line.substring(10).trim();
                emit(out, indent, "Joytopia.broadcast(" + expression(value) + ");");
                continue;
            }

            if (line.startsWith("call ")) {
                emit(out, indent, line.substring(5).trim() + ";");
                continue;
            }

            if (line.startsWith("return ")) {
                emit(out, indent, "return " + expression(line.substring(7).trim()) + ";");
                continue;
            }

            if (line.startsWith("local ")) {
                String assignment = line.substring(6).trim();
                emit(out, indent, "let " + assignment + (assignment.endsWith(";") ? "" : ";"));
                continue;
            }

            if (line.startsWith("const ")) {
                String assignment = line.substring(6).trim();
                emit(out, indent, "const " + assignment + (assignment.endsWith(";") ? "" : ";"));
                continue;
            }

            if (line.startsWith("--")) continue;

            // Pass through common JavaScript-style assignments and calls.
            if (line.matches("[A-Za-z_$][A-Za-z0-9_$]*\\s*=.*") || line.matches("[A-Za-z_$][A-Za-z0-9_$]*\\(.*\\)")) {
                emit(out, indent, line.endsWith(";") ? line : line + ";");
                continue;
            }

            error(filename, lineNumber, "unknown statement: " + line);
        }

        if (indent != 0) error(filename, lines.size(), "missing 'end'");
        return out.toString();
    }

    private static String insideCall(String line, String name, String filename, int lineNumber) throws LESCException {
        int open = line.indexOf('(');
        int close = line.lastIndexOf(')');
        if (open < 0 || close < open) error(filename, lineNumber, "invalid " + name + " call");
        return line.substring(open + 1, close).trim();
    }

    private static String expression(String value) {
        String result = value.trim();
        result = result.replace("~=", "!=");
        result = result.replace("==", "===");
        result = result.replace(" and ", " && ");
        result = result.replace(" or ", " || ");
        result = result.replace(" not ", " !");
        result = result.replace(" true", " true").replace(" false", " false");
        if (result.equals("true")) return "true";
        if (result.equals("false")) return "false";
        return result;
    }

    private static String stripComment(String line) {
        boolean quoted = false;
        char quote = 0;
        for (int i = 0; i < line.length() - 1; i++) {
            char c = line.charAt(i);
            if ((c == '"' || c == '\'') && (i == 0 || line.charAt(i - 1) != '\\')) {
                if (!quoted) { quoted = true; quote = c; }
                else if (quote == c) quoted = false;
            }
            if (!quoted && c == '-' && line.charAt(i + 1) == '-') return line.substring(0, i);
        }
        return line;
    }

    private static void validateIdentifier(String name, String filename, int line) throws LESCException {
        if (!name.matches("[A-Za-z_$][A-Za-z0-9_$]*")) error(filename, line, "invalid function name: " + name);
    }

    private static void emit(StringBuilder out, int indent, String text) {
        out.append("  ".repeat(Math.max(0, indent))).append(text).append('\n');
    }

    private static void error(String filename, int line, String message) throws LESCException {
        throw new LESCException(filename + ":" + line + ": " + message);
    }

    private static class LESCException extends Exception {
        LESCException(String message) { super(message); }
    }
}
