import java.io.IOException;
import java.nio.file.*;

/** LESC -> JavaScript compiler for Joytopia 2. */
public class LESC {
    public static void main(String[] args) throws Exception {
        if (args.length < 1 || args.length > 2) {
            System.err.println("Usage: java LESC <input.lesc> [output.js]");
            System.exit(1);
        }
        Path input = Paths.get(args[0]);
        Path output = args.length == 2 ? Paths.get(args[1]) : replaceExtension(input, ".js");
        String source = Files.readString(input);
        Files.createDirectories(output.toAbsolutePath().getParent());
        Files.writeString(output, compile(source, input.toString()));
        System.out.println("LESC compiled: " + input + " -> " + output);
    }

    static Path replaceExtension(Path p, String ext) {
        String n = p.getFileName().toString();
        int dot = n.lastIndexOf('.');
        if (dot >= 0) n = n.substring(0, dot);
        Path parent = p.getParent();
        return parent == null ? Paths.get(n + ext) : parent.resolve(n + ext);
    }

    static String compile(String source, String file) throws Exception {
        StringBuilder out = new StringBuilder("// Generated by LESC for Joytopia 2\n");
        int indent = 0;
        String[] lines = source.replace("\r", "").split("\n", -1);
        for (int i = 0; i < lines.length; i++) {
            String s = stripComment(lines[i]).trim();
            if (s.isEmpty()) continue;
            int line = i + 1;
            if (s.equals("end")) {
                if (indent == 0) fail(file, line, "unexpected end");
                indent--; emit(out, indent, "}"); continue;
            }
            if (s.startsWith("function ")) {
                String d = s.substring(9).trim();
                if (!d.matches("[A-Za-z_$][A-Za-z0-9_$]*\\s*\\(.*\\)")) fail(file,line,"invalid function");
                emit(out, indent++, "function " + d + " {"); continue;
            }
            if (s.startsWith("if ")) {
                String c=s.substring(3).trim(); if(c.endsWith(" then")) c=c.substring(0,c.length()-5).trim();
                emit(out,indent++,"if ("+expr(c)+") {"); continue;
            }
            if (s.equals("else")) { if(indent==0) fail(file,line,"else without if"); indent--; emit(out,indent++,"} else {"); continue; }
            if (s.startsWith("while ")) { String c=s.substring(6).trim(); if(c.endsWith(" do")) c=c.substring(0,c.length()-3).trim(); emit(out,indent++,"while ("+expr(c)+") {"); continue; }
            if (s.startsWith("repeat ")) { emit(out,indent++,"for (let __i=0; __i<"+expr(s.substring(7).trim())+"; __i++) {"); continue; }
            if (s.startsWith("print(") || s.startsWith("print (")) { emit(out,indent,"console.log"+s.substring(s.indexOf('('))+";"); continue; }
            if (s.startsWith("alert(") || s.startsWith("alert (")) { emit(out,indent,"window.alert"+s.substring(s.indexOf('('))+";"); continue; }
            if (s.startsWith("wait(") || s.startsWith("wait (")) { String a=callArg(s,file,line); emit(out,indent,"await new Promise(r => setTimeout(r, "+expr(a)+" * 1000));"); continue; }
            if (s.equals("spawn()") || s.equals("spawn ()")) { emit(out,indent,"Joytopia.spawn();"); continue; }
            if (s.startsWith("broadcast ")) { emit(out,indent,"Joytopia.broadcast("+expr(s.substring(10).trim())+");"); continue; }
            if (s.startsWith("call ")) { emit(out,indent,s.substring(5).trim()+";"); continue; }
            if (s.startsWith("return ")) { emit(out,indent,"return "+expr(s.substring(7).trim())+";"); continue; }
            if (s.startsWith("local ")) { emit(out,indent,"let "+finish(s.substring(6).trim())); continue; }
            if (s.startsWith("const ")) { emit(out,indent,"const "+finish(s.substring(6).trim())); continue; }
            if (s.matches("[A-Za-z_$][A-Za-z0-9_$]*(\\.[A-Za-z_$][A-Za-z0-9_$]*)*\\s*=.*") || s.matches(".*\\(.*\\).*")) emit(out,indent,finish(s));
            else fail(file,line,"unknown statement: "+s);
        }
        if(indent!=0) fail(file,lines.length,"missing end");
        return out.toString();
    }

    static String finish(String s){ return s.endsWith(";")?s:s+";"; }
    static String callArg(String s,String f,int l)throws Exception{ int a=s.indexOf('('),b=s.lastIndexOf(')'); if(a<0||b<a)fail(f,l,"invalid call"); return s.substring(a+1,b).trim(); }
    static String expr(String s){ return s.replace("~=","!=").replace(" and "," && ").replace(" or "," || ").replace(" not "," !"); }
    static String stripComment(String s){ boolean q=false; char qc=0; for(int i=0;i<s.length()-1;i++){char c=s.charAt(i);if((c=='\"'||c=='\'')&&(i==0||s.charAt(i-1)!='\\')){if(!q){q=true;qc=c;}else if(qc==c)q=false;}if(!q&&c=='-'&&s.charAt(i+1)=='-')return s.substring(0,i);}return s; }
    static void emit(StringBuilder o,int n,String s){o.append("  ".repeat(Math.max(0,n))).append(s).append('\n');}
    static void fail(String f,int l,String m)throws Exception{throw new Exception(f+":"+l+": "+m);}
}
